### ISSUE TITLE
Update xwf 20.0 broke something

### ISSUE THREAD

**Issue by Banaanhangwagen** [a5hlynx/xt_fuzzy#1]
While importing the extension, I get the following error:
![image](https://user-images.githubusercontent.com/25983612/80712275-0cd18d80-8af2-11ea-95fd-6061bc6b1a28.png)

Tested on XWF v20.0 preview 6

**Comment by a5hlynx** [comment]
Hi, Banaanhangwagen-san

Currently, this x-tension can not be loaded by preview version of X-Ways Forensics. Please wait until SR version is released, and try it again.

If you'd like to use the x-tension with preview version, modify the code in xt_fuzzy/ssdeep.cpp as follows and build the solution. The generated dll would be loadable by preview version.

```diff
@@ -108,8 +108,7 @@

        if ( (XT_INIT_XWF & nFlags) == 0 ||
                  XT_INIT_WHX & nFlags ||
-                 XT_INIT_XWI & nFlags ||
-                 XT_INIT_BETA & nFlags
+                 XT_INIT_XWI & nFlags
        ){
                return -1;
        }
```
